CREATE DATABASE IF NOT EXISTS ATM;

USE ATM;

-- Table to store user information
CREATE TABLE IF NOT EXISTS USERS (
    VCN VARCHAR(60) PRIMARY KEY,
    PHN CHAR(10) UNIQUE NOT NULL,
    PIN CHAR(4) NOT NULL,
    BALANCE float8 DEFAULT 1
);

-- Table to store transaction history
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID BIGINT PRIMARY KEY,
    VCN VARCHAR(60),
    VCN2 VARCHAR(60),
    AMOUNT INT,
    TRANSACTION_TYPE VARCHAR(60),
    FOREIGN KEY (VCN) REFERENCES USERS(VCN),
    FOREIGN KEY (VCN2) REFERENCES USERS(VCN) 
);